import json
import os
from datetime import datetime

def save_report(ioc, ioc_type, enrichment_data, ai_report):
    """Save the full report as JSON and text file."""

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_ioc = ioc.replace(".", "_").replace("/", "_")
    base_filename = f"reports/{safe_ioc}_{timestamp}"

    full_report = {
        "ioc": ioc,
        "ioc_type": ioc_type,
        "timestamp": datetime.now().isoformat(),
        "enrichment_data": enrichment_data,
        "ai_analyst_report": ai_report
    }

    # Save JSON
    with open(f"{base_filename}.json", "w") as f:
        json.dump(full_report, f, indent=2)

    # Save readable text report
    with open(f"{base_filename}.txt", "w") as f:
        f.write("=" * 60 + "\n")
        f.write("   AI-POWERED THREAT INTELLIGENCE ENRICHMENT REPORT\n")
        f.write("=" * 60 + "\n\n")
        f.write(f"IOC       : {ioc}\n")
        f.write(f"Type      : {ioc_type}\n")
        f.write(f"Timestamp : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        f.write("-" * 60 + "\n")
        f.write("RAW ENRICHMENT DATA\n")
        f.write("-" * 60 + "\n")
        for source_data in enrichment_data:
            f.write(f"\n{source_data.get('source', 'Unknown Source')}\n")
            for key, value in source_data.items():
                if key != "source":
                    f.write(f"  {key:<20}: {value}\n")
        f.write("\n" + "=" * 60 + "\n")
        f.write("AI ANALYST REPORT\n")
        f.write("=" * 60 + "\n\n")
        f.write(ai_report)
        f.write("\n\n" + "=" * 60 + "\n")
        f.write("Generated by AI-Powered Threat Intel Enrichment Tool\n")
        f.write("Built by Sai Kollu | github.com/sai-kollu\n")
        f.write("=" * 60 + "\n")

    print(f"\n✅ Reports saved to {base_filename}.json and .txt")
    return base_filename